apiVersion: v1
kind: Secret
metadata:
  name: service-secret
type: Opaque
data:
  order-service-secret-key: M2UwMjVlMTYtNGQ3OC0xMWVkLWJkYzMtMDI0MmFjMTIwMDAy
  REDIS_PASSWORD: YVVRMFVubENSR3c1YUE9PQ==
