---
apiVersion: v1
kind: Service
metadata:
  name: property-service
spec:
  type: LoadBalancer
  selector:
    app: property
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
#      nodePort: 30009
