---
apiVersion: v1
kind: ConfigMap
metadata:
  name: account-config

data:
  SERVICE_PORT: "8080"
  DB_KEYSPACE_NAME: account_ks
  DB_DATA_CENTER: datacenter1
  DB_PORT: 9042
  DB_CONTACT_POINT: account-db
  KAFKA_BOOTSTRAP_SERVER: localhost:9092
  KAFKA_GET_TOPIC: GET_ACCOUNT_EVENT
  KAFKA_RESPONSE_TOPIC: RESPONSE_GET_ACCOUNT_EVENT
  KAFKA_CREATED_TOPIC: ACCOUNT_CREATED_EVENT